In [1]:
import pandas as pd

In [2]:
simulation = pd.read_parquet("simulation.parquet")
validation = pd.read_parquet("validation.parquet")
simulation_30 = pd.read_parquet("simulation_30.parquet")

FileNotFoundError: [Errno 2] No such file or directory: 'simulation_30.parquet'

In [3]:
simulation

,power_draw,energy_usage,cpu_usage,cpu_utilization,host_name,cluster_name,timestamp,timestamp_absolute
0,32.165581,9610.521484,447594.0,0.048091,H01,C01,300000,1664575500000
1,31.752739,9556.804688,421806.0,0.045320,H01,C01,600000,1664575800000
2,31.713406,9516.906250,419349.0,0.045056,H01,C01,900000,1664576100000
3,31.572540,9534.303711,410550.0,0.044111,H01,C01,1200000,1664576400000
4,31.469666,9447.032227,404124.0,0.043421,H01,C01,1500000,1664576700000
...,...,...,...,...,...,...,...,...
8648,36.230137,10520.837891,701484.0,0.075370,H01,C01,2594700000,1667169900000
8649,36.016655,10946.159180,688149.0,0.073937,H01,C01,2595000000,1667170200000
8650,35.319057,10652.760742,644574.0,0.069255,H01,C01,2595300000,1667170500000
8651,35.313004,10613.628906,644196.0,0.069215,H01,C01,2595600000,1667170800000
8652,35.313004,0.000000,644196.0,0.069215,H01,C01,2595600000,1667170800000

In [4]:
validation

              timestamp-date-time    host  power_draw  energy_usage  timestamp
0       2022-10-11 16:05:30+02:00  r27n18        44.0        1320.0      30000
1       2022-10-11 16:06:00+02:00  r27n18        44.0        1320.0      60000
2       2022-10-11 16:06:30+02:00  r27n18        44.0        1320.0      90000
3       2022-10-11 16:07:00+02:00  r27n18        44.0        1320.0     120000
4       2022-10-11 16:07:30+02:00  r27n18        44.0        1320.0     150000
...                           ...     ...         ...           ...        ...
3260563 2022-10-09 21:36:00+02:00   r27n9        32.0         960.0 -152940000
3260564 2022-10-12 05:08:00+02:00   r27n9        32.0         960.0   46980000
3260565 2022-10-12 02:00:00+02:00   r27n9        32.0         960.0   35700000
3260566 2022-10-09 03:33:00+02:00   r27n9        32.0         960.0 -217920000
3260567 2022-10-10 03:52:30+02:00   r27n9        32.0         960.0 -130350000

[5584043 rows x 5 columns]